### ISSUE TITLE
Says no song playing on macOS 10.15

### ISSUE THREAD

**Issue by diamkil** [kevinmussi/iTunes-Discord-RP#10]
On macOS 10.15 Catalina the iTunes app is replaced by a new Music app and the app doesn't detect it and simply says no song playing

**Comment by kevinmussi** [comment]
I don't have a Mac that supports 10.15, so I don't have any way to make it compatible with the new app currently, sorry!

**Comment by diamkil** [comment]
you can actually install Catalina on unsupported mac or I could use my mac for your tests

**Comment by 23Aaron** [comment]
Just tested on 10.15.1 with the latest discord version and it works flawlessly! Thank you! @kevinmussi

**Comment by diamkil** [comment]
> I released a new version which should also be compatible with Catalina, but I haven't been able to test it (since I'm on an older version). It should work, but I'd be grateful if someone could confirm that.

works well, only thing missing is running it as menu bar app
