### ISSUE TITLE
Application does not use correct Text Encoding

### ISSUE THREAD

**Issue by SunTheCourier** [kevinmussi/iTunes-Discord-RP#11]
Text for things like details and state should be using UTF8 or else some characters are not correctly interpreted by Discord

![image](https://user-images.githubusercontent.com/22406854/71290271-43b5bc80-2324-11ea-99df-36ff1d669dc0.png)

**Comment by kevinmussi** [comment]
I never experienced that issue on Mac, I guess you're running it on Windows?

**Comment by SunTheCourier** [comment]
yep

**Comment by kevinmussi** [comment]
Ok, I'll look into that. Hopefully that will also solve the [issue](https://github.com/kevinmussi/iTunes-Discord-RP/issues/8#issue-431268180) with Japanese characters.

**Comment by SunTheCourier** [comment]
I don't believe JPN characters are in UTF8?
