### ISSUE TITLE
Only works for Apple Music tracks in library

### ISSUE THREAD

**Issue by jrub1** [kevinmussi/iTunes-Discord-RP#16]
I don't know if this is intended or not or a limitation of the Music/iTunes app, but this is only detecting played songs that are added to my Apple Music library (and not things from random playlists/albums not added to my library). I think this should be possible since last.fm scribblers are able to read tracks played not in the user's library? But I may be wrong.

**Comment by lferezy4** [comment]
Anyt updates on this?

**Comment by kevinmussi** [comment]
What do you mean by "things from random playlists/albums not added to my library"? The application should detect everything that gets played within the iTunes/Music app.

**Comment by lferezy4** [comment]
If your listening to apple music from a station (i.e https://music.apple.com/us/station/hip-hop/ra.985488923) It doesnt detect it on the application that your listening to music but if you listen to a song you purchased it detects it

**Comment by kevinmussi** [comment]
Ah, I see. I'll have to look into that, if it's even possible to work with those kinds of tracks, because I remember that also happened to me when listening to song previews in the store.

**Comment by jrub1** [comment]
To clarify, when you have added Apple Music tracks to your library and plays them, it works fine. But if you are using Apple Music to stream music not added to your library (like albums, playlists, or radio stations as mentioned above), then the app does not show the tracks. I'm realizing this application may be intended to only work with locally-stored iTunes tracks and not with the Apple Music service though.

**Comment by kevinmussi** [comment]
> I'm realizing this application may be intended to only work with locally-stored iTunes tracks and not with the Apple Music service though
You're right, but I also assumed it would also work with streamed music, but since it doesn't it must mean that those use a different protocol or format, I'll have to see if it can be worked with.

**Comment by Techno3600** [comment]
This happens to me also.

**Comment by kevinmussi** [comment]
The issue has been fixed in the [latest release](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest), thanks goes to @cawc for finding the fix for it.
