### ISSUE TITLE
No status in Discord for me

### ISSUE THREAD

**Issue by xjrimus** [kevinmussi/iTunes-Discord-RP#17]
Doesn't work for me. The track playing can be seen inside the Java application but the status in Discord won't change. Also no error in Console, see below.

`PS D:\Downloads> java -jar .\iTunesDiscordRP-1.3.exe
Apr 14, 2020 1:04:08 PM com.github.kevinmussi.itunesrp.Main main
INFORMATION: Application started running.
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.Main main
INFORMATION: View invoked.
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.preferences.PreferencesManager readPreferencesFromFile
INFORMATION: Preferences correctly read from file.
13:04:09.332 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.entities.pipe.Pipe - Searching for IPC: \\?\pipe\discord-ipc-0
13:04:09.341 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.entities.pipe.Pipe - Sent packet: Pkt:HANDSHAKE{"v":1,"nonce":"0ee04ccb-627a-4482-ad26-9d35e4c5741f","client_id":"473069598804279309"}
13:04:09.520 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.entities.pipe.WindowsPipe - Received packet: Pkt:FRAME{"evt":"READY","data":{"v":1,"config":{"environment":"production","api_endpoint":"//d
iscordapp.com/api","cdn_host":"cdn.discordapp.com"},"user":{"premium_type":0,"bot":false,"flags":32,"id":"374207236706271252","avatar":null,"username":"dreadmyspike","discriminator":"9179"}},"cmd":"DI
SPATCH","nonce":null}
13:04:09.521 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.entities.pipe.Pipe - Found a valid client (STABLE) with packet: Pkt:FRAME{"evt":"READY","data":{"v":1,"config":{"environment":"production",
"api_endpoint":"//discordapp.com/api","cdn_host":"cdn.discordapp.com"},"user":{"premium_type":0,"bot":false,"flags":32,"id":"374207236706271252","avatar":null,"username":"dreadmyspike","discriminator"
:"9179"}},"cmd":"DISPATCH","nonce":null}
13:04:09.521 [AWT-EventQueue-0] INFO com.jagrosh.discordipc.entities.pipe.Pipe - Found preferred client: STABLE
13:04:09.521 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.IPCClient - Client is now connected and ready!
13:04:09.523 [AWT-EventQueue-0] DEBUG com.jagrosh.discordipc.IPCClient - Starting IPCClient reading thread!
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.core.DiscordHelper$CommandReceiver connect
INFORMATION: Client successfully connected.
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.core.ScriptHelper executeScript
INFORMATION: The script started execution.
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.core.DiscordHelper onUpdate
INFORMATION: Received new track.
13:04:09.676 [Thread-3] DEBUG com.jagrosh.discordipc.IPCClient - Sending RichPresence to discord: {"assets":{"small_image":"playing","small_text":"Playing","large_image":"itunes-logo","large_text":"iT
unes"},"instance":true,"timestamps":{"start":1586862180},"details":"­ƒÄÂ Yellow","state":"­ƒæñ Emmit Fenn ­ƒÆ┐ Yellow - Single","secrets":{},"party":{"size":[1,1],"id":"aa"}}
13:04:09.685 [Thread-3] DEBUG com.jagrosh.discordipc.entities.pipe.Pipe - Sent packet: Pkt:FRAME{"args":{"activity":{"assets":{"small_image":"playing","small_text":"Playing","large_image":"itunes-logo
","large_text":"iTunes"},"instance":true,"timestamps":{"start":1586862180},"details":"­ƒÄÂ Yellow","state":"­ƒæñ Emmit Fenn ­ƒÆ┐ Yellow - Single","secrets":{},"party":{"size":[1,1],"id":"aa"}},"pid":1
3764},"cmd":"SET_ACTIVITY","nonce":"8ce521e8-188d-482f-b78c-db92c0a3c328"}
Apr 14, 2020 1:04:09 PM com.github.kevinmussi.itunesrp.core.DiscordHelper onUpdate
INFORMATION: Updated Rich Presence.
13:04:09.726 [Thread-2] DEBUG com.jagrosh.discordipc.entities.pipe.WindowsPipe - Received packet: Pkt:FRAME{"evt":null,"data":{"assets":{"small_image":"473554687535349760","small_text":"Playing","larg
e_image":"473143286102622229","large_text":"iTunes"},"timestamps":{"start":1586862180000},"name":"Music","flags":1,"details":"­ƒÄÂ Yellow","state":"­ƒæñ Emmit Fenn ­ƒÆ┐ Yellow - Single","secrets":{},"
application_id":"473069598804279309","party":{"size":[1,1],"id":"aa"}},"cmd":"SET_ACTIVITY","nonce":"8ce521e8-188d-482f-b78c-db92c0a3c328"}`

Discord:
Stable 58100 (26efe4c)
Host 0.0.306

Windows 10 64-Bit (10.0.18363)

**Comment by kevinmussi** [comment]
This sounds weird, after you're connected to the Discord app, and if the tracks show up in the java window, then it should appear in your status. Are you sure you're not set as "invisible" on Discord? Because in that case Discord won't show your rich presence, even if you're the one who's checking.

**Comment by xjrimus** [comment]
I had the option "show game activity" deactivated. Didn't think it's categorized the same as games. Thanks for the hint.
