### ISSUE TITLE
[Request] Have running as background or menu bar app for macOS

### ISSUE THREAD

**Issue by alicerunsonfedora** [kevinmussi/iTunes-Discord-RP#2]
It would be nice to be able to run the app in the background as a menu bar app on the Mac instead of it taking place on the Dock. I'm not quite sure if this is possible in Swing, but it's worth looking into.

**Comment by kevinmussi** [comment]
That would be actually a good thing to have. Apparently it's possible to do it using an awt component, I'll look into adding it (hoping it works with Swing).

**Comment by harpalassi** [comment]
This would be great.

**Comment by cryptographic1337** [comment]
+1 This would be awesome.

**Comment by kevinmussi** [comment]
I finally added a menu bar toggle in the [latest release](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest). Sadly I couldn't hide the app icon in the dock, because it would break the GUI as it is now, but at least you can use it to hide the app's main window while it is running.
