### ISSUE TITLE
Is there a way to change the icons?

### ISSUE THREAD

**Issue by tacojam** [kevinmussi/iTunes-Discord-RP#21]
I was wondering if I can change the iTunes icon, I'm presuming it's getting the image via the internet as the icon doesn't match my one. Don't mind if i cannot, but thanks for the app. :)

**Comment by kevinmussi** [comment]
Mh not really, but what I could do is, if using MacOS 10.15, to change the icon to the new one. Would that be alright?

**Comment by kevinmussi** [comment]
I added a new window to choose which image to show (or if to show no image at all) in the [new release](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest), I hope that's good for you :)
