### ISSUE TITLE
End of album/playlist song stuck on "playing"

### ISSUE THREAD

**Issue by jrub1** [kevinmussi/iTunes-Discord-RP#23]
Hi,

On Windows 10, occasionally when I reach the end of an album or playlist, it gets stuck saying I'm still "playing" the track, with the duration elapsed counter going up infinitely. For instance, this track is only 4 minutes but it says it's been playing for over 15:

![image](https://user-images.githubusercontent.com/6395917/84216353-1b5e7d80-aa7e-11ea-8d0d-18c16311f256.png)

**Comment by kevinmussi** [comment]
Hey, thanks for pointing this out, this is actually a very obvious issue I didn't catch. It should be fixed now in the [latest release](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest).
