### ISSUE TITLE
JRELoadError on the .app version.

### ISSUE THREAD

**Issue by rikupone** [kevinmussi/iTunes-Discord-RP#27]
the .jar version works fine, but i want to keep this app in my dock for easy access

![image](https://user-images.githubusercontent.com/49787675/87742015-c3820780-c7dd-11ea-8a39-4ab29f803710.png)

**Comment by kevinmussi** [comment]
Try reinstalling the latest JRE as said [here](https://github.com/kevinmussi/iTunes-Discord-RP/issues/9#issuecomment-655647641).

**Comment by rikupone** [comment]
> Try reinstalling the latest JRE as said [here](https://github.com/kevinmussi/iTunes-Discord-RP/issues/9#issuecomment-655647641).

works perfectly. thanks!
