### ISSUE TITLE
Extending Song Title

### ISSUE THREAD

**Issue by ericg689** [kevinmussi/iTunes-Discord-RP#30]
Is there a way to extend the appearance of the song title in the Discord status? For example, in the image below the full song title is "Round & Round (Extended Mix)." However, I only see what I see in the screenshot. Any way to fix this?
![Screen Shot 2020-07-30 at 5 56 43 PM](https://user-images.githubusercontent.com/42044611/88978608-089e4300-d28e-11ea-992f-47615d9d27bd.png)

**Comment by kevinmussi** [comment]
That must be left over from when I made the status layout change, and of course I didn't test it with long names, I'll fix it as soon as possible.

**Comment by kevinmussi** [comment]
It should be fixed now in [v1.5.4](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest).
