### ISSUE TITLE
Not working—giving error

### ISSUE THREAD

**Issue by Eiszett** [kevinmussi/iTunes-Discord-RP#4]
For the past couple of months, this hasn't been working.
I'm on Mac OS X 10.10.5, Discord 0.0.254 and iTunes 12.8.0.150
Whenever I try to connect, it tells me:

> An error has occurred while trying to connect to Discord!
Make sure that:
• You have the Discord app installed and currently running.
• You're logged in with your account.

**Comment by kevinmussi** [comment]
I don't have a way to test this on an old OS X version. Can you run the .jar file through the terminal and paste here the output you receive when trying to connect? (Download the jar file, then do `java -jar iTunesDiscordRP-1.1.jar`)

**Comment by Eiszett** [comment]
Attempting that got Terminal to inform me that I needed the Java Development Kit to attempt that.

Now that that's been done, there are no issues whatsoever. Doesn't answer why it stopped working, but oh well. Thank you.

**Comment by kevinmussi** [comment]
Oh I didn't know that the JDK was required, I'll add that to the readme! Glad it works now
