### ISSUE TITLE
Support for iTunes in Wine on Linux?

### ISSUE THREAD

**Issue by Austcool-Walker** [kevinmussi/iTunes-Discord-RP#5]
Hi in the future could there be support for iTunes in wine on GNU/Linux?
![image](https://user-images.githubusercontent.com/29024076/53310717-073c4000-387c-11e9-82a9-54294acd52dc.png)

**Comment by kevinmussi** [comment]
Hi, I don't think there's a way to connect with an application running in a Wine wrapper (or at least I have no idea how that could be done), sorry!
